In [9]:
import numpy as np
import os

In [16]:
# Q1(a)
arr = np.array([1, 2, 3, 6, 4, 5])
reversed= arr[::-1]
print(f"Original: {arr}")
print(f"Reversed: {reversed}")

Original: [1 2 3 6 4 5]
Reversed: [5 4 6 3 2 1]


In [18]:
# Q1(b)
array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
flattened1 = array1.flatten()
print(f"\nFlattened1: {flattened1}")
flattened2 = array1.ravel()
print(f"Flattened2: {flattened2}")


Flattened1: [1 2 3 2 4 5 1 2 3]
Flattened2: [1 2 3 2 4 5 1 2 3]


In [21]:
# Q1(c)
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])

print(f"Array 1:\n{arr1}")
print(f"\nArray 2:\n{arr2}")
compare = arr1 == arr2
print(f"\nCompare Element-wise :\n{compare}")

equal = np.array_equal(arr1, arr2)
print(f"Array equal:\n {equal}")
equality = np.all(arr1 == arr2)
print(f"elements equal: \n{equality}")

Array 1:
[[1 2]
 [3 4]]

Array 2:
[[1 2]
 [3 4]]

Compare Element-wise :
[[ True  True]
 [ True  True]]
Array equal:
 True
elements equal: 
True


In [22]:
# Q1(d)
x = np.array([1,2,3,4,5,1,2,1,1,1])
unique_x, counts_x = np.unique(x, return_counts=True)
most_frequent_x = unique_x[np.argmax(counts_x)]
indices_x = np.where(x == most_frequent_x)[0]
print(f"Array x: {x}")
print(f"Most frequent value: {most_frequent_x}")
print(f"Indices of mfv: {indices_x}")
print(f"Frequency: {np.max(counts_x)}\n")

y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
unique_y, counts_y = np.unique(y, return_counts=True)
most_frequent_y = unique_y[np.argmax(counts_y)]
indices_y = np.where(y == most_frequent_y)[0]
print(f"\nArray y: {y}")
print(f"Most frequent value: {most_frequent_y}")
print(f"Indices ofmfv: {indices_y}")
print(f"Frequency: {np.max(counts_y)}")

Array x: [1 2 3 4 5 1 2 1 1 1]
Most frequent value: 1
Indices of mfv: [0 5 7 8 9]
Frequency: 5


Array y: [1 1 1 2 3 4 2 4 3 3]
Most frequent value: 1
Indices ofmfv: [0 1 2]
Frequency: 3


In [24]:
# Q1(e)
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
print(f"Matrix gfg:\n{gfg}")
total_sum = np.sum(gfg)
print(f"\nSum of all elements: {total_sum}")
row_sum = np.sum(gfg, axis=1)
print(f"\nrow-wise Sum:\n{row_sum}")
col_sum = np.sum(gfg, axis=0)
print(f"\ncolumn-wise Sum:\n{col_sum}")

Matrix gfg:
[[ 4  1  9]
 [12  3  1]
 [ 4  5  6]]

Sum of all elements: 45

row-wise Sum:
[[14]
 [16]
 [15]]

column-wise Sum:
[[20  9 16]]


In [25]:
# Q1(f)
n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])
print(f"Matrix n_array:\n{n_array}")
diagonal_sum = np.trace(n_array)
print(f"\n Sum of diagonal elements: {diagonal_sum}")

eigenvalues, eigenvectors = np.linalg.eig(n_array)
print(f"\n Eigen values:\n{eigenvalues}")
print(f"\n Eigen vectors:\n{eigenvectors}")

matrix_inverse = np.linalg.inv(n_array)
print(f"\n Inverse of matrix:\n{matrix_inverse}")

determinant = np.linalg.det(n_array)
print(f"\n Determinant of matrix: {determinant}")

Matrix n_array:
[[55 25 15]
 [30 44  2]
 [11 45 77]]

 Sum of diagonal elements: 176

 Eigen values:
[28.097044   49.73460452 98.16835147]

 Eigen vectors:
[[-0.34637121  0.15017693  0.4574917 ]
 [ 0.72784061  0.4852124   0.28447814]
 [-0.59184038 -0.8614034   0.84248058]]

 Inverse of matrix:
[[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]

 Determinant of matrix: 137180.0000000001


In [26]:
# Q1(g)

p1 = np.array([[1, 2], [2, 3]])
q1 = np.array([[4, 5], [6, 7]])

print("FIRST PAIR:")
print(f"Matrix p1:\n{p1}")
print(f"Matrix q1:\n{q1}")

multiplication1 = np.dot(p1, q1)
print(f"\n Matrix multiplication p1 × q1:\n{multiplication1}")

covariance1 = np.cov(p1.flatten(), q1.flatten())
print(f"\n Covariance between p1 and q1:\n{covariance1}")

print("\n" + "*"*50)

p2 = np.array([[1, 2], [2, 3], [4, 5]])
q2 = np.array([[4, 5, 1], [6, 7, 2]])

print("\nSECOND PAIR:")
print(f"Matrix p2:\n{p2}")
print(f"Matrix q2:\n{q2}")

multiplication2 = np.dot(p2, q2)
print(f"\nMatrix multiplication p2 × q2:\n{multiplication2}")

covariance2 = np.cov(p2.flatten(), q2.flatten())
print(f"\nCovariance between p2 and q2:\n{covariance2}")

FIRST PAIR:
Matrix p1:
[[1 2]
 [2 3]]
Matrix q1:
[[4 5]
 [6 7]]

 Matrix multiplication p1 × q1:
[[16 19]
 [26 31]]

 Covariance between p1 and q1:
[[0.66666667 1.        ]
 [1.         1.66666667]]

**************************************************

SECOND PAIR:
Matrix p2:
[[1 2]
 [2 3]
 [4 5]]
Matrix q2:
[[4 5 1]
 [6 7 2]]

Matrix multiplication p2 × q2:
[[16 19  5]
 [26 31  8]
 [46 55 14]]

Covariance between p2 and q2:
[[2.16666667 0.23333333]
 [0.23333333 5.36666667]]


In [10]:
# Q1(h)
import numpy as np
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])

print(f"Matrix x:\n{x}")
print(f"Matrix y:\n{y}")

inner_product = np.inner(x, y)
print(f"\nInner product:\n{inner_product}")

outer_product = np.outer(x, y)
print(f"\nOuter product:\n{outer_product}")

x_flat = x.flatten()
y_flat = y.flatten()
cartesian_x, cartesian_y = np.meshgrid(x_flat, y_flat, indexing='ij')
cartesian_product = np.stack([cartesian_x.ravel(), cartesian_y.ravel()], axis=-1)
print(f"\nCartesian product (first 10 pairs):\n{cartesian_product[:10]}")
print(f"Total cartesian product pairs: {len(cartesian_product)}")

Matrix x:
[[2 3 4]
 [3 2 9]]
Matrix y:
[[ 1  5  0]
 [ 5 10  3]]

Inner product:
[[17 52]
 [13 62]]

Outer product:
[[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]

Cartesian product (first 10 pairs):
[[ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]]
Total cartesian product pairs: 36


In [27]:
# Q2(a)
import numpy as np
array = np.array([[1, -2, 3],[-4, 5, -6]])
abs_array = np.abs(array)
print(f"\nABSOLUTE VALUES:\n{abs_array}")

flattened = array.flatten()
print(f"\nPERCENTILES:")
print(f"Flattened array: {flattened}")

p25_flat = np.percentile(flattened, 25)
p50_flat = np.percentile(flattened, 50)
p75_flat = np.percentile(flattened, 75)
print(f"\nFlattened array - 25th percentile: {p25_flat}")
print(f"Flattened array - 50th percentile: {p50_flat}")
print(f"Flattened array - 75th percentile: {p75_flat}")

p25_col = np.percentile(array, 25, axis=0)
p50_col = np.percentile(array, 50, axis=0)
p75_col = np.percentile(array, 75, axis=0)
print(f"\nColumn-wise - 25th percentile: {p25_col}")
print(f"Column-wise - 50th percentile: {p50_col}")
print(f"Column-wise - 75th percentile: {p75_col}")

p25_row = np.percentile(array, 25, axis=1)
p50_row = np.percentile(array, 50, axis=1)
p75_row = np.percentile(array, 75, axis=1)
print(f"\nRow-wise - 25th percentile: {p25_row}")
print(f"Row-wise - 50th percentile: {p50_row}")
print(f"Row-wise - 75th percentile: {p75_row}")

print(f"\nSTATISTICS:")

mean_flat = np.mean(flattened)
median_flat = np.median(flattened)
std_flat = np.std(flattened)
print(f"\nFlattened array - Mean: {mean_flat}")
print(f"Flattened array - Median: {median_flat}")
print(f"Flattened array - Standard Deviation: {std_flat}")

mean_col = np.mean(array, axis=0)
median_col = np.median(array, axis=0)
std_col = np.std(array, axis=0)
print(f"\nColumn-wise - Mean: {mean_col}")
print(f"Column-wise - Median: {median_col}")
print(f"Column-wise - Standard Deviation: {std_col}")

mean_row = np.mean(array, axis=1)
median_row = np.median(array, axis=1)
std_row = np.std(array, axis=1)
print(f"\nRow-wise - Mean: {mean_row}")
print(f"Row-wise - Median: {median_row}")
print(f"Row-wise - Standard Deviation: {std_row}")


ABSOLUTE VALUES:
[[1 2 3]
 [4 5 6]]

PERCENTILES:
Flattened array: [ 1 -2  3 -4  5 -6]

Flattened array - 25th percentile: -3.5
Flattened array - 50th percentile: -0.5
Flattened array - 75th percentile: 2.5

Column-wise - 25th percentile: [-2.75 -0.25 -3.75]
Column-wise - 50th percentile: [-1.5  1.5 -1.5]
Column-wise - 75th percentile: [-0.25  3.25  0.75]

Row-wise - 25th percentile: [-0.5 -5. ]
Row-wise - 50th percentile: [ 1. -4.]
Row-wise - 75th percentile: [2.  0.5]

STATISTICS:

Flattened array - Mean: -0.5
Flattened array - Median: -0.5
Flattened array - Standard Deviation: 3.8622100754188224

Column-wise - Mean: [-1.5  1.5 -1.5]
Column-wise - Median: [-1.5  1.5 -1.5]
Column-wise - Standard Deviation: [2.5 3.5 4.5]

Row-wise - Mean: [ 0.66666667 -1.66666667]
Row-wise - Median: [ 1. -4.]
Row-wise - Standard Deviation: [2.05480467 4.78423336]


In [13]:
# Q2(b)
import numpy as np
a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])
floor= np.floor(a)
print(f"\nFloor: {floor}")

ceiling = np.ceil(a)
print(f"Ceiling: {ceiling}")

truncated= np.trunc(a)
print(f"Truncated: {truncated}")

rounded = np.round(a)
print(f"Rounded: {rounded}")


Floor: [-2. -2. -1.  0.  1.  1.  3.]
Ceiling: [-1. -1. -0.  1.  2.  2.  3.]
Truncated: [-1. -1. -0.  0.  1.  1.  3.]
Rounded: [-2. -2. -0.  0.  2.  2.  3.]


In [14]:
# Q3(a)
import numpy as np
array = np.array([10, 52, 62, 16, 16, 54, 453])
print(f"Original array: {array}")

sorted_array = np.sort(array)
print(f"\nSorted array: {sorted_array}")

sorted_indices = np.argsort(array)
print(f"\nIndices of sorted array: {sorted_indices}")
print(f"Verification - array[sorted_indices]: {array[sorted_indices]}")

four_smallest_indices = np.argpartition(array, 4)[:4]
four_smallest = array[four_smallest_indices]
four_smallest_sorted = np.sort(four_smallest)
print(f"\n4 smallest elements: {four_smallest_sorted}")

five_largest_indices = np.argpartition(array, -5)[-5:]
five_largest = array[five_largest_indices]
five_largest_sorted = np.sort(five_largest)[::-1]
print(f"\n5 largest elements: {five_largest_sorted}")

Original array: [ 10  52  62  16  16  54 453]

Sorted array: [ 10  16  16  52  54  62 453]

Indices of sorted array: [0 3 4 1 5 2 6]
Verification - array[sorted_indices]: [ 10  16  16  52  54  62 453]

4 smallest elements: [10 16 16 52]

5 largest elements: [453  62  54  52  16]


In [15]:
# Q3(b)
import numpy as np
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
print(f"Original array: {array}")

integer_mask = array == array.astype(int)
integer_elements = array[integer_mask]
print(f"\nInteger elements only: {integer_elements}")

float_mask = array != array.astype(int)
float_elements = array[float_mask]
print(f"\nFloat elements only (non-integer): {float_elements}")

print(f"\nDetailed breakdown:")
print(f"Original array: {array}")
print(f"As integers: {array.astype(int)}")
print(f"Integer mask: {integer_mask}")
print(f"Float mask: {float_mask}")

Original array: [1.  1.2 2.2 2.  3.  2. ]

Integer elements only: [1. 2. 3. 2.]

Float elements only (non-integer): [1.2 2.2]

Detailed breakdown:
Original array: [1.  1.2 2.2 2.  3.  2. ]
As integers: [1 1 2 2 3 2]
Integer mask: [ True False False  True  True  True]
Float mask: [False  True  True False False False]
